----------------------------DROP PROCEDURE GENERALES------------------------------
DROP PROCEDURE INTEGRASGO.SP_INTSGO_GEN_REGISTRO_CLIENTE 
GO
DROP PROCEDURE INTEGRASGO.SP_INTSGO_GEN_REGISTRA_REPRESENTANTE 
GO
DROP PROCEDURE INTEGRASGO.SP_INTSGO_GEN_ACTUALIZA_REPRESENTANTE 
GO
DROP PROCEDURE INTEGRASGO.SP_INTSGO_GEN_GENERARNUMERADOR 
GO
DROP PROCEDURE INTEGRASGO.SP_INTSGO_GEN_LISTADO_COMPANIA 
GO
DROP PROCEDURE INTEGRASGO.SP_INTSGO_GEN_LISTADO_DIVISION 
GO
DROP PROCEDURE INTEGRASGO.SP_INTSGO_GEN_LISTADO_PLANTA 
GO
DROP PROCEDURE INTEGRASGO.SP_INTSGO_GEN_LISTADO_CLIENTE 
GO
DROP PROCEDURE INTEGRASGO.SP_INTSGO_GEN_LISTADO_TIPOOPERACION 
GO
DROP PROCEDURE INTEGRASGO.SP_INTSGO_GEN_LISTADO_TIPOALMACEN 
GO
DROP PROCEDURE INTEGRASGO.SP_INTSGO_GEN_LISTADO_FINANCIADOR 
GO
DROP PROCEDURE INTEGRASGO.SP_INTSGO_GEN_LISTADO_ALMACEN 
GO
DROP PROCEDURE INTEGRASGO.SP_INTSGO_GEN_LISTADO_MONEDA 
GO
DROP PROCEDURE INTEGRASGO.SP_INTSGO_GEN_LISTADO_REGIMEN 
GO
DROP PROCEDURE INTEGRASGO.SP_INTSGO_GEN_LISTADO_ADUANAS 
GO
DROP PROCEDURE INTEGRASGO.SP_INTSGO_GEN_LISTADO_CIASEGURO 
GO
DROP PROCEDURE INTEGRASGO.SP_INTSGO_GEN_LISTADO_UBIGEO 
GO
DROP PROCEDURE INTEGRASGO.SP_INTSGO_GEN_LISTADO_FAMILIA 
GO
DROP PROCEDURE INTEGRASGO.SP_INTSGO_GEN_LISTADO_PRODUCTO 
GO
DROP PROCEDURE INTEGRASGO.SP_INTSGO_GEN_LISTADO_UNIDADMEDIDA 