--drop procedure DC@DESLIB.SP_INTSGO_GEN_ILOG


CREATE OR REPLACE PROCEDURE DC@RNSLIB.SP_INTSGO_GEN_ILOG(	
	IN pNOMSRV varchar(100),
	IN pPRMSRV varchar(2000),
	IN pRESSRV varchar(100)
)
LANGUAGE SQL
BEGIN

	DECLARE pFCHCRT numeric(8,0) DEFAULT 0;
	DECLARE pNCRRLT numeric(4,0) DEFAULT 0;
	DECLARE pHRACRT numeric(6,0) DEFAULT 0;
	
	SET pFCHCRT=YEAR(CURRENT DATE)*10000 + MONTH(CURRENT DATE)*100 + DAY(CURRENT DATE);
	SET pHRACRT=HOUR(CURRENT TIME)*10000 + MINUTE(CURRENT TIME)*100 + SECOND(CURRENT TIME);
	
	SELECT IFNULL(MAX(NCRRLT),0) INTO pNCRRLT FROM DC@RNSLIB.ZZWMLG;
	
	INSERT INTO DC@RNSLIB.ZZWMLG (FCHCRT, HRACRT, NCRRLT, NOMSRV, PRMSRV, RESSRV)
	VALUES (pFCHCRT, pHRACRT, pNCRRLT+1, pNOMSRV, pPRMSRV, pRESSRV );

END


--SELECT * FROM DC@DESLIB.ZZWMLG